# Generated by Django 3.0.6 on 2020-05-11 06:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import store_management.products.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('landing_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='MRP')),
                ('distributor_margin', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Shell Margin')),
                ('retailer_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.PositiveIntegerField()),
                ('barcode_entry', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=store_management.products.utils.get_product_upload_path)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductExpiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Product Expiry',
                'verbose_name_plural': 'Products Expiry',
            },
        ),
        migrations.CreateModel(
            name='ProductStockChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.IntegerField()),
                ('changeType', models.CharField(choices=[('INITIAL_STOCK', 'Initial Stock'), ('SHIFT', 'Shift'), ('ADDITION', 'Addition'), ('DEDUCTION', 'Deduction')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'Product Stock Change',
                'verbose_name_plural': 'Product Stock Changes',
            },
        ),
    ]
