# Generated by Django 3.0.6 on 2020-05-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200511_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_entry',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
