# Generated by Django 3.0.6 on 2020-05-09 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200509_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.IntegerField()),
                ('changeType', models.CharField(choices=[('INITIAL_STOCK', 'Initial Stock'), ('SHIFT', 'Shift'), ('ADDITION', 'Addition'), ('DEDUCTION', 'Deduction')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Stock Change',
                'verbose_name_plural': 'Product Stock Changes',
            },
        ),
    ]
