# Generated by Django 3.0.6 on 2020-05-18 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20200511_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='productexpiry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productstockchange',
            name='changeType',
            field=models.CharField(choices=[('INITIAL_STOCK', 'Initial Stock'), ('SHIFT', 'Shift'),
                                            ('SHIFT_MODIFICATION', 'Shift Modification'), ('ADDITION', 'Addition'),
                                            ('DEDUCTION', 'Deduction')], max_length=50),
        ),
    ]
