# Generated by Django 3.0.6 on 2020-06-21 11:09

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_auto_20200518_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                      verbose_name='created'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                           verbose_name='modified'),
        ),
    ]
