# Generated by Django 3.0.6 on 2020-05-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        ('products', '0004_productstockchange_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockchange',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='shifts.ShiftDetail'),
        ),
    ]
