# Generated by Django 3.0.6 on 2020-05-11 06:10

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDetail',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_dt', models.DateTimeField(verbose_name='Start Date/Time')),
                ('end_dt', models.DateTimeField(verbose_name='End Date/Time')),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distributor_margin_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retailer_margin_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Detail',
                'verbose_name_plural': 'Shift Details',
            },
        ),
        migrations.CreateModel(
            name='ShiftEntry',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('distributor_margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Shell Margin')),
                ('retailer_margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.ShiftDetail')),
            ],
            options={
                'verbose_name': 'Shift Entry',
                'verbose_name_plural': 'Shift Entry',
            },
        ),
    ]
