# Generated by Django 3.0.6 on 2020-05-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200511_0614'),
        ('shifts', '0002_auto_20200511_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_entries', to='products.Product'),
        ),
    ]
