# Generated by Django 3.0.6 on 2020-05-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200511_0614'),
        ('shifts', '0004_auto_20200515_1359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftentry',
            unique_together={('shift', 'product')},
        ),
    ]
