# Generated by Django 3.0.6 on 2020-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shifts', '0005_auto_20200517_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftdetail',
            name='approved',
        ),
        migrations.AddField(
            model_name='shiftdetail',
            name='status',
            field=models.CharField(
                choices=[('NEW', 'New'), ('WAITING_FOR_APPROVAL', 'Waiting For Approval'), ('APPROVED', 'Approved')],
                default='NEW', max_length=50),
        ),
    ]
